name = "BayesInteractomics"
uuid = "07c96638-0f98-4a6b-9a09-78dfb944548d"
desc = "Bayesian framework for analyzing protein interactome data from AP-MS and proximity labeling experiments"
version = "0.1.0"
authors = ["Manuel Seefelder <manuel.seefelder@uni-ulm.de>"]

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
Copulas = "ae264745-0b69-425e-9d9d-cf662c5eec93"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJScikitLearnInterface = "5ae90465-5518-4432-b9d2-8a1def2f0cab"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RxInfer = "86711068-29c9-4ff7-b620-ae75d7495b3d"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[weakdeps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"

[extensions]
BayesInteractomicsNetworkExt = ["Graphs", "SimpleWeightedGraphs", "GraphPlot", "Compose", "Cairo"]

[compat]
Aqua = "0.8, 0.9"
BenchmarkTools = "1.6.3"
CSV = "0.10"
Cairo = "1"
Colors = "0.12, 0.13"
Compose = "0.9"
Copulas = "0.1"
DataFrames = "1"
Distributions = "0.25"
DocStringExtensions = "0.9, 0.10"
Flux = "0.14, 0.15, 0.16"
GraphPlot = "0.5"
Graphs = "1.7"
HDF5 = "0.17, 0.18"
JLD2 = "0.4, 0.5, 0.6"
LaTeXStrings = "1"
LogExpFunctions = "0.3"
LoggingExtras = "1"
MLJ = "0.20, 0.21, 0.22"
MLJScikitLearnInterface = "0.4, 0.5, 0.6, 0.7"
MultivariateStats = "0.10, 0.11"
Optim = "1.13.3"
ProgressMeter = "1"
QuadGK = "2"
Random = "1"
RxInfer = "2, 3, 4"
SimpleWeightedGraphs = "1.4"
Statistics = "1"
StatsBase = "0.33, 0.34"
StatsPlots = "0.15, 0.16"
TestItemRunner = "1"
ThreadsX = "0.1"
XLSX = "0.10, 0.11"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimpleWeightedGraphs = "47aef6b3-ad0c-573a-a1e2-d07658019622"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Aqua", "CSV", "Compose", "GraphPlot", "Graphs", "SimpleWeightedGraphs", "Test", "TestItemRunner", "Random", "Statistics"]
